# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 50, 800, 600))
        self.groupBox.setObjectName("groupBox")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 560, 780, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.ReplaceButton = QtWidgets.QPushButton(self.groupBox)
        self.ReplaceButton.setGeometry(QtCore.QRect(660, 520, 93, 28))
        self.ReplaceButton.setObjectName("ReplaceButton")
        self.StoreButton = QtWidgets.QPushButton(self.groupBox)
        self.StoreButton.setGeometry(QtCore.QRect(560, 520, 93, 28))
        self.StoreButton.setObjectName("StoreButton")
        self.PathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PathLineEdit.setGeometry(QtCore.QRect(180, 70, 600, 20))
        self.PathLineEdit.setObjectName("PathLineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 40, 150, 20))
        self.label.setObjectName("label")
        self.NameComboBox = QtWidgets.QComboBox(self.groupBox)
        self.NameComboBox.setGeometry(QtCore.QRect(180, 40, 531, 20))
        self.NameComboBox.setObjectName("NameComboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(35, 70, 150, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(49, 100, 120, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 150, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(65, 160, 150, 20))
        self.label_5.setObjectName("label_5")
        self.CompileLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CompileLineEdit.setGeometry(QtCore.QRect(180, 100, 600, 20))
        self.CompileLineEdit.setObjectName("CompileLineEdit")
        self.HostLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.HostLineEdit.setGeometry(QtCore.QRect(180, 130, 600, 20))
        self.HostLineEdit.setObjectName("HostLineEdit")
        self.ConIDLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ConIDLineEdit.setGeometry(QtCore.QRect(180, 160, 600, 20))
        self.ConIDLineEdit.setObjectName("ConIDLineEdit")
        self.LogTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.LogTextBrowser.setGeometry(QtCore.QRect(50, 320, 701, 192))
        self.LogTextBrowser.setObjectName("LogTextBrowser")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 72, 15))
        self.label_6.setObjectName("label_6")
        self.AddPushButton = QtWidgets.QPushButton(self.groupBox)
        self.AddPushButton.setGeometry(QtCore.QRect(720, 40, 60, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(6)
        self.AddPushButton.setFont(font)
        self.AddPushButton.setObjectName("AddPushButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "微服务替换助手 - liuxinhao4@huawei.com"))
        self.groupBox.setTitle(_translate("mainWindow", "服务可执行文件替换"))
        self.ReplaceButton.setText(_translate("mainWindow", "执行替换"))
        self.StoreButton.setText(_translate("mainWindow", "保存"))
        self.label.setText(_translate("mainWindow", "任务名称："))
        self.label_2.setText(_translate("mainWindow", "可执行文件目录："))
        self.label_3.setText(_translate("mainWindow", "编译机IP地址："))
        self.label_4.setText(_translate("mainWindow", "服务宿主机IP地址："))
        self.label_5.setText(_translate("mainWindow", "服务容器ID："))
        self.LogTextBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ok</p></body></html>"))
        self.label_6.setText(_translate("mainWindow", "日志："))
        self.AddPushButton.setText(_translate("mainWindow", "添加"))
